apiVersion: v1
kind: Secret
metadata:
  name: airbnb-secrets
  namespace: default
type: Opaque
stringData:
  JWT_SECRET: "change-this-in-production-use-base64-encoded-string"
  MONGODB_ROOT_USERNAME: "admin"
  MONGODB_ROOT_PASSWORD: "adminpassword"
  TAVILY_API_KEY: "your-tavily-api-key-here"
